config/routes.rb
Rails.application.routes.draw do
  root 'excel_reader#index'
  post 'upload', to: 'excel_reader#upload'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/excel_reader_controller.rb
class ExcelReaderController < ApplicationController
  def index
    @data = session.delete(:uploaded_data) || []
  end

  def upload
    uploaded_file = params[:file]
    spreadsheet = Roo::Spreadsheet.open(uploaded_file.path)

    @data = spreadsheet.sheet(0).parse(headers: true)

    # Store data in session to display it after redirect
    session[:uploaded_data] = @data

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/excel_reader_helper.rb
module ExcelReaderHelper
end

app/views/excel_reader/_uploaded_data.html.erb
<% if data.present? %>
  <h2>Uploaded Data</h2>
  <table border="1">
    <thead>
      <tr>
        <% data.first.keys.each do |key| %>
          <th><%= key %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% data.each do |row| %>
        <tr>
          <% row.values.each do |value| %>
            <td><%= value %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/excel_reader/index.html.erb
<h1>Upload Excel File</h1>

<%= form_with url: upload_path, local: false, multipart: true do |form| %>
  <%= form.file_field :file %>
  <%= form.submit 'Upload' %>
<% end %>

<% if @data.present? %>
  <h2>Uploaded Data</h2>
  <table border="1">
    <thead>
      <tr>
        <% @data.first.keys.each do |key| %>
          <th><%= key %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @data.each do |row| %>
        <tr>
          <% row.values.each do |value| %>
            <td><%= value %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/excel_reader/upload.html.erb
Hello
<%debugger%>
<div id="uploaded_data">
  <%= render partial: "uploaded_data", locals: { data: @data } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExcelReader</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>